### PR TITLE
Youtube: fix repeated scrobbling

### LINKED ISSUE #918: Scrobble youtube repeat
After pressing repeat button which appears instead of play button after the video finishes, scrobbling starts again - which is perfectly fine.

However, when using repeat function added by Magic Actions extension 
or 
right-clicking video and selecting Loop - scrobbling won't start again. It just stays on Scrobbled (song name), no matter how many times video gets repeated.

Is it just me? Am I doing something wrong? Or is this "function" not added yet. If so, would you consider looking into it, perhaps working it out somehow?

Thanks for great extension though ;-)

### PR DESCRIPTION
**Pull request by f1u77y**
- Listen to timeupdate events generated by `<video>` element instead of
using MutationObserver
- Use `currentTime` and `duration` properties of `<video>` element
instead of text values in `.ytp-time-*`

Fixes #918

UPD: progress -> timeupdate

### CODE REVIEW

**Comment by alexesprit** [comment]
The updated connector doesn't recognize now playing song because `videoSelector` has never class `playing-mode`.

```diff
diff --git a/connectors/v2/youtube.js b/connectors/v2/youtube.js
index 5edd041..cb2f517 100644
--- a/connectors/v2/youtube.js
+++ b/connectors/v2/youtube.js
@@ -68,7 +68,7 @@ Connector.getUniqueID = function() {
 };

 Connector.isPlaying = function() {
-       return $(this.videoSelector).hasClass('playing-mode');
+       return $('#player-api .html5-video-player').hasClass('playing-mode');
 };

 Connector.isStateChangeAllowed = function() {
```

**Comment by f1u77y** [comment]
Whoops, that was ".html5-video-player" class, haven't noticed that. Reverted

**Comment by f1u77y** [comment]
(and I'm wary of the fact that progress events are generated very rarely(1 time per ~6 secs), so sometimes there can be no progress events at the last 5% of song and it won't be marked for repeat)

**Comment by alexesprit** [comment]
@f1u77y I noticed you call the `Connector.onStateChanged` function directly. In this case the result of the `Connector.isStateChangeAllowed` function is ignored.

**Comment by f1u77y** [comment]
> In this case the result of the `Connector.isStateChangeAllowed` function is ignored

OK but isn't it better just to use this function inside default implementation of `Connector.onStateChanged` rather then outside of it? (I see you're talking about the same)

> The video element generates 'progress' events about 8-10 times per song

Ahh, I misused this event(it's about *loading* progress but not *playing*). Will fix.

**Comment by f1u77y** [comment]
> Is there a way to watch these events somewhere in dev console?

`monitorEvents`

**Comment by alexesprit** [comment]
> monitorEvents

Ok, thanks.

Seems like the connector works fine.

> OK but isn't it better just to use this function inside default implementation of Connector.onStateChanged rather then outside of it?

Yep, I meant the same thing.

File: connectors/v2/youtube.js [hunk 1]
```diff
@@ -14,10 +14,28 @@ chrome.storage.local.get('Connectors', function(data) {
 	}
 });
 
-Connector.playerSelector = '#page';
+Connector.videoSelector = '#player-api .html5-main-video';
+
+{
+	$(Connector.videoSelector).on('timeupdate', () => {
+		if (Connector.isStateChangeAllowed()) {
```
Comment (alexesprit) [inline connectors/v2/youtube.js]: I'm just wondering why did you put event listener setup into curly braces? Is there a certain reason for that?

Comment (f1u77y) [inline connectors/v2/youtube.js]: To show that's a separate block for setup(not sure if it's needed because the whole file is connector setup)

**Comment by alexesprit** [comment]
@f1u77y I noticed some regression after merging this PR. Here are steps to reproduce:
1. Open Youtube front page.
2. Select any music video that should be recognized by the extension.

The selected music video won't be recognized, but it actually should.

Can you reproduce the issue? If so, have you any thoughts on how to fix it w/o reverting the commit?

**Comment by f1u77y** [comment]
Yes, that's because the video loads in the same page. We should search for the video element with `MutationObserver`

**Comment by alexesprit** [comment]
@f1u77y Ideally we should also stop search if video element is found and start search again if video element is missing on the page (e.g. user moves back on front page).

**Comment by alexesprit** [comment]
@f1u77y https://github.com/alexesprit/web-scrobbler/commit/5e92958834ba3c021581f44b29b24a0c0d55980b perhaps looks too complicated but I don't know how to simplify the code/reimplement by using another approach . Have you a better solution?

**Comment by f1u77y** [comment]
I wrote mostly the same code, and I don't see any way to do it in a better way.
(BTW, usage of `MutationObserver` with all flags on looks like overkill, doesn't it?)

**Comment by alexesprit** [comment]
Ok, so I'll commit these changes, since I don't want to revert this PR.

> (BTW, usage of MutationObserver with all flags on looks like overkill, doesn't it?)

I enabled only two flags which are required to observe visibility state of the video element.

**Comment by alexesprit** [comment]
Youtube changed something on their website, so the connector from this PR works fine again.
