### PR TITLE
Fix Deezer connector

### LINKED ISSUE #536: problems with deezer
hi, I've got problems with scrobbling from deezer, last.fm scrobbler doesn't recognize any song/track. When used in other services (for ex. youtube) everything seems ok.

### PR DESCRIPTION
**Pull request by alexesprit**
Resolves #536 #541 #560.

Additional changes:
* added current time/duration processing;
* added track art.

### CODE REVIEW

File: connectors/v2/deezer.js [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+
+/* global Connector */
+
+Connector.playerSelector = '#page_sidebar';
+
+Connector.getArtist = function() {
+	var artists = $.map($('.player-track-artist').children(), function(artist) {
+		return $.text(artist);
+	});
+	return artists.join(', ');
```
Comment (inverse) [inline connectors/v2/deezer.js]: This doesn't look like it makes sense to me? Are things really that wacky on the page?

Comment (alexesprit) [inline connectors/v2/deezer.js]: That's an example how an artists element looks:
```html
<h3 class="player-track-artist heading-2-sub ellipsis">
    <!-- react-text: 1666 -->from<!-- /react-text -->
    <!-- react-text: 1667 -->&nbsp;<!-- /react-text -->
    <!-- react-text: 1668 --><!-- /react-text -->
    <span class="player-track-link" data-action="link" data-href="/artist/282118">Major Lazer</span>
    <!-- react-text: 1670 -->, <!-- /react-text -->
    <span class="player-track-link" data-action="link" data-href="/artist/288166">Justin Bieber</span>
    <!-- react-text: 1672 -->, <!-- /react-text -->
    <span class="player-track-link" data-action="link" data-href="/artist/4333887">MO</span>
</h3>
```
If `player-track-artist` is used as selector, the actual artist is 'from Major Lazer, Justin Bieber, MO'. Of course, artists can be extracted by splitting the whole string by non-breaking space and taking the second part of the string. But I think it's not a good way. So I decided to get children of `.player-track-artist`, convert them to an array of strings and join by comma.
